project_name: stackgraph
version: 2

builds:
  - env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    main: ./cmd/stackgraph
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
#    no_unique_dist_dir: true # we need unique dist dirs to build multi-arch docker images
    binary: '{{ .ProjectName }}' # _v{{ .Version }} # DONE: Decide if we want to keep the _v there instead of just _, pipeline needs to be adjusted if changed
snapshot:
  version_template: '{{ incpatch .Version }}'
archives:
  - formats:
    - zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      # if you are using this is a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate it's not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  draft: false
changelog:
  use: git # or remove below and just use: github-native
  filters:
    include:
      - "^feat:"
      - "^fix:"
      - "^chore:"
      - "^docs:"
  sort: asc # Sort commits chronologically (oldest to newest)
  groups:   # organize your changelog into categories using regular expressions, start commit with feat: or fix:
    # https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional
    - title: '🛠 Dependency updates'
      regexp: '^fix\(deps\):|^feat\(deps\):'
      order: 300
    - title: '✨ New Features'
      regexp: '^feat(\([^)]*\))?:'
      order: 100
    - title: '🐛 Bug fixes'
      regexp: '^fix(\([^)]*\))?:'
      order: 200
    - title: '📖 Documentation updates'
      regexp: '^docs(\([^)]*\))?:'
      order: 400
    - title: '🛡️ Security updates'
      regexp: '^sec(\([^)]*\))?:'
      order: 500
    - title: '🚀 Build process updates'
      regexp: '^(build|ci)(\([^)]*\))?:'
      order: 600
    - title: '📦 Other work'
      regexp: '^chore(\([^)]*\))?:|^chore:'
      order: 9999

# To check deprecations:
# https://goreleaser.com/deprecations/
